### ISSUE TITLE
Test refactor

### ISSUE THREAD

**Issue by mknorps** [tweag/FawltyDeps#166]
As we advance in the complexity of objects representing the FD domain, our test code also grows in complexity. 
It takes notably more time to change the test code base when changing the basic objects that are being tested.

We should:

- [ ] rethink the structure of tests, as discussed with the team, to test one feature at a time (for example change in `Location` object should not propagate to all tests using `UndeclaredDependencies`)
- [x] gather common helper functions in `utils.py` and refactor tests cases to use them
- [ ] Use more fixtures not to repeat test cases between tests files and/or generate test cases automatically
- [x] Consider using objects with reasonable defaults for `pytest.param` inputs (test in `compare_imports_to_dependencies) have now 5 variables, for which most is just an empty list
- [x] (may be a separate issue) Consider using `hypothesis` for property-based testing

**Comment by jherland** [comment]
This issue was discussed in today's status meeting, and a couple of points from the meeting notes are worth repeating here:
- Testing with hypothesis is very valuable, but applying it at the CLI level is too slow. Write hypothesis tests directly against the `Analysis` object instead.
- Focus more on testing with the `Analysis` object. It should be our main test “surface” esp. if FD ends up being used as a library.
- Rephrase CLI tests as Settings+Analysis tests. Not having to go through a subprocess will speed these tests up considerably.
-  (for later:) Consider the overlap of "sample projects" defined in `tests/conftest.py` vs. the projects in `tests/sample_projects`.
