### ISSUE TITLE
Properly handling command-line options that take multiple values

### ISSUE THREAD

**Issue by jherland** [tweag/FawltyDeps#211]
Tangentially related to [this slack thread](https://tweag.slack.com/archives/C04AAQP8C85/p1678287577829779), I'm noticing some weird (maybe not wrong) interaction with the command line interface when you want to pass multiple values. This applies to `--ignore-undeclared` and `--ignore-unused` (and soon `--code` and `--deps`, see #156 and #210). I'm gonna use `--ignore-unused` only in the following examples:

1. Not given: `fawltydeps --generate-toml-config` ==> `ignore_unused = []` ✅
2. Missing arg: `fawltydeps --generate-toml-config --ignore-unused` ==> argparse error ✅
3. Empty arg: `fawltydeps --generate-toml-config --ignore-unused ""` ==> `ignore_unused = ['']` acceptable corner case IMHO ✅
4. Empty arg 2: `fawltydeps --generate-toml-config --ignore-unused=` ==> `ignore_unused = ['']` acceptable corner case IMHO ✅
5. Single arg: `fawltydeps --generate-toml-config --ignore-unused foo` ==> `ignore_unused = ['foo']` ✅
6. Single arg 2: `fawltydeps --generate-toml-config --ignore-unused=foo` ==> `ignore_unused = ['foo']` ✅
7. Two args:  `fawltydeps --generate-toml-config --ignore-unused foo bar` ==> `ignore_unused = ['foo', 'bar']` ✅
8. Two args 2:  `fawltydeps --generate-toml-config --ignore-unused foo --ignore-unused bar` ==> `ignore_unused = ['bar']` (the second overrides the first) ❓
9. Two args 3:  `fawltydeps --generate-toml-config --ignore-unused=foo bar` ==> `ignore_unused = ['foo']` (the second arg is interpreted as basepath) ❗❓
10. Two args 4: `fawltydeps --generate-toml-config --ignore-unused=foo --ignore-unused=bar` ==> `ignore_unused = ['bar']` (the second overrides the first) ❓
11. Two args 5: `fawltydeps --generate-toml-config --ignore-unused=foo,bar` ==> `ignore_unused = ['foo,bar']` (interpreted as one arg with comma embedded, not really unexpected) ❓
12. Two args 6: `fawltydeps --generate-toml-config --ignore-unused="foo bar"` ==> `ignore_unused = ['foo bar']` (interpreted as one arg with space embedded, also not really unexpected) ❓

I'm sure there are more variations we could play around with...

- Cases 1-7 are straightforward, however if the user fails to find case 7 as the only valid way to pass two args to these options, they are likely to get confused:
- Case 8 and 10 are maybe the two cases that _should_ have been handled better by us, as it's fairly obvious what the user is _trying_ to do.
- Case 9 can be interpreted either way without being "wrong" IMHO, which makes it hard to known how we should handle it. I'm partial to following argparse's default behavior and just say that's the way it is.
- Cases 11-12 are examples of what a struggling user might attempt, but handling these would require some extra parsing on our side, which is hard to get right if we also want to support paths that contain spaces/commas...

**Comment by vreuter** [comment]
I will try to make cases for / against the behavior in cases 8-12...
8. That is a bit odd, I agree; the expectation I'd have would be a two-element list, rather than an override. I'm not sure we can control this, but would be OK modifying the behavior if we can.
9. This seems totally normal to me; the `--<opt>=<arg>` effectively resulting in a sort of "tighter binding" thereby enabling more natural placement of the positional arg at the end (as is sort of alluded to in the 3rd point of your 2nd comment.
10. I feel exactly the same as Case 8; I'd expect them to behave the same, but not how they do in your example. If we change, we should make sure these cases match.

Cases 11 and 12 totally make sense to me, insofar as the default behavior is concerned (how else would a delimited string be passed otherwise?). I guess it's _OK_ if we change the behavior here, but I think that we'd be taking a step away from what's intuitive (and doing some work for perhaps a relatively rare use case)

**Comment by vreuter** [comment]
I think with #247 merged, from my view, somewhat stated in the discussion above, this issue is largely or entirely solved and could be closed. I guess for a definitive ruling we may need to have a group discussion about sensible / tolerable / preferred behavior. @Nour-Mws @mknorps @jherland what do you think?

**Comment by jherland** [comment]
AFAICS #247 solves case 8 and case 10 above 🥳. For case 9 I think we agree(?) that the currrent behavior makes sense. (I like your phrasing that `=` "binds tighter" than space, and I think I could defend view that in a future discussion 😉)

That leaves case 11 and 12 which I agree are of zero/negative importance.

Hence I think the status quo after #247 is good, and we can close this. 👍🏻
